#!/usr/bin/python
#
# generate-rps-data - create data suitable for rock-paper-scissors portion
#   of the red-green game
#
# use with: generate-rps-data >rps.py
# use:
#   $ generate-rps-data >rps-candidate.py
#
# then examine data for desired randomness
#   $ vi rps-candidate.py
#
# then make it live:
#   $ cp rps-candidate.py rgdata/rps.py
#
# and restart uwsgi:
#   $ ./stop_uwsgi
#   $ ./start_uwsgi
#

import random

print("""# rps data for the rock-paper-scissors portion of the red-green game
# to be imported by rg.cgi
# this file represents the "host throw" for each numbered round

rps_data = {""")

throws = ["rock", "paper", "scissors"]

for i in range(1,50):
    n = random.randint(0, 2)
    rps = throws[n]
    print('    %d: "%s",' % (i,rps))

print("}")

