# rps data for the rock-paper-scissors portion of the red-green game
# to be imported by rg.cgi
# this file represents the "host throw" for each numbered round

rps_data = {
    1: "scissors",
    2: "rock",
    3: "paper",
    4: "rock",
    5: "rock",
    6: "paper",
    7: "paper",
    8: "scissors",
    9: "rock",
    10: "paper",
    11: "scissors",
    12: "scissors",
    13: "paper",
    14: "scissors",
    15: "rock",
    16: "paper",
    17: "scissors",
    18: "rock",
    19: "rock",
    20: "rock",
    21: "rock",
    22: "paper",
    23: "scissors",
    24: "rock",
    25: "paper",
    26: "paper",
    27: "scissors",
    28: "scissors",
    29: "scissors",
    30: "scissors",
    31: "scissors",
    32: "rock",
    33: "paper",
    34: "scissors",
    35: "scissors",
    36: "paper",
    37: "scissors",
    38: "rock",
    39: "rock",
    40: "scissors",
    41: "rock",
    42: "scissors",
    43: "rock",
    44: "paper",
    45: "rock",
    46: "paper",
    47: "scissors",
    48: "paper",
    49: "paper",
}
